{ pkgs, ... }: {
  xdg.configFile = {
    nvim = {
      source = ./nvim;
      recursive = true;
    };
  };
  # programs.neovim = {
  # enable = true;
  # generatedConfigs = {
  # lua = ''
  # -- Generated by home-manager
  # vim.opt.background = "dark"
  # '';
  # };
  # plugins = with pkgs.vimPlugins; [ vim-surround ];
  # };
}
